### ISSUE TITLE
Enhance Maildir support

### ISSUE THREAD

**Issue by tommairs** [KumoCorp/kumomta#109]
The current maildir support is rudimentary and adequate for basic testing but should be made more robust and save mail files sorted by user name and potentially by domain.  This would enable installing Dovecot or some other webmail interface for management.

Current docs are here: https://docs.kumomta.com/reference/kumo/make_queue_config/?h=maildir#example-of-using-the-maildir-protocol

Ideally, there should be options for where to locate the message store and set dir and file permissions:

  basedir = "/var/tmp/maildir"
  dirmode = 775
  filemode = 664

There should also be options for creating new folders based on the localpart of the destination address and optionally to create dirs based on the domains as well.    IE: /var/tmp/maildir/new/kumomta.com/tom/
  create_users = true
  create_domain_paths = true

FInally, there should be options to capture mail for all domains or only for select domains.
  all_domains = false 
  domains = ( "example.com", "kumomta.com" )

**Comment by wez** [comment]
I think the way to go here is to enable `maildir_path` to be processed with minijinja, passing it the envelope recipient and a copy of the full meta object from the message. 

https://docs.kumomta.com/reference/kumo/make_queue_config/protocol/#example-of-using-the-maildir-protocol

```lua
return kumo.make_queue_config {
    protocol = {
      maildir_path = '/var/tmp/kumo-maildir/{{ domain }}/{{ user }}',
    },
}
```

Since this will likely need to coordinate ownership of the directory structure with other processes, offering control over the file and directory modes is important, so expanding https://github.com/KumoCorp/kumomta/blob/2037371793df4b6b615af224e3ad22c6a622524a/crates/maildir/src/lib.rs#L625 to pass down the dir and file modes is important.

This is where we store incoming mail to maildir:
https://github.com/KumoCorp/kumomta/blob/2037371793df4b6b615af224e3ad22c6a622524a/crates/kumod/src/queue.rs#L1674-L1701

Here's how we set up minijinja in the logging code:
https://github.com/KumoCorp/kumomta/blob/2037371793df4b6b615af224e3ad22c6a622524a/crates/kumod/src/logging/mod.rs#L124-L137

https://github.com/KumoCorp/kumomta/blob/2037371793df4b6b615af224e3ad22c6a622524a/crates/kumod/src/logging/files.rs#L239

https://github.com/KumoCorp/kumomta/blob/2037371793df4b6b615af224e3ad22c6a622524a/crates/kumod/src/logging/files.rs#L317-L323
