### ISSUE TITLE
[Enhancement] DKIM-Signature header includes headers (in h= tag) that do not present in actual email

### ISSUE THREAD

**Issue by INBOXWISE** [KumoCorp/kumomta#110]
### What Operating System are you seeing this problem on?

Ubuntu 22.04.3 LTS

### What Hardware is this system running?

Google Cloud Platform

### KumoMTA version

2023.11.28-b5252a41

### Did you try the latest release to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I appreciate the flexibility provided by the current configuration options, particularly within the dkim_data.toml file.

However, I have identified an improvement that could enhance the precision and efficiency of DKIM-Signature headers. Currently, the MTA includes headers as specified in the dkim_data.toml file, regardless of whether these headers are present in the email itself.

I propose that DKIM-Signature headers only include the headers specified in the dkim_data.toml file if and only if those headers are present in the actual email.

### Configuration

```
# The default set of headers to sign to include
headers = ["CC", "List-Id", "Resent-Date", "Content-Description", "List-Owner", "Resent-From", "Content-Id", "List-Post", "Resent-Message-ID", "Content-Transfer-Encoding", "List-Subscribe", "Resent-Sender", "Content-Type", "List-Unsubscribe", "List-Unsubscribe-Post", "Resent-To", "Date", "MIME-Version", "Sender", "From", "Message-ID", "Subject", "In-Reply-To", "References", "To", "List-Archive", "Reply-To", "List-Help", "Resent-Cc"]
```

### Expected Behavior

KumoMTA was supposed to include only the following headers in DKIM-Signature: header as only these were present in the email.

`h=Date:To:From:Subject:Message-Id
`

**Comment by wez** [comment]
The current behavior is because DKIM signatures can attest that the listed headers were *not* present in the original mail; this excerpt is from https://www.rfc-editor.org/rfc/rfc6376.html#section-5.4

> Signers MAY claim to have signed header fields that do not exist
   (that is, Signers MAY include the header field name in the "h=" tag
   even if that header field does not exist in the message).  When
   computing the signature, the nonexisting header field MUST be treated
   as the null string (including the header field name, header field
   value, all punctuation, and the trailing CRLF).

   >>   INFORMATIVE RATIONALE: This allows Signers to explicitly assert
      the absence of a header field; if that header field is added
      later, the signature will fail.

If we were to make header signing conditional on the header being present, it would need to be through an additional separate option so that the sender can choose which behavior they desire.

What is your objection to the current behavior?  Is it because the default in the docs is a rather long list of headers that are not always present, and it results in a larger signature header?  Is the size of the signature header an issue in practice?

Would it perhaps be reasonable to change that example to something shorter?

**Comment by MHillyer** [comment]
Over signing missing headers helps to prevent DKIM replay attacks where a malicious party adds headers that were not in the header list, and is a desirable feature. If there was an error or automatic filter on missing headers from showing in the header list, this security feature would not be possible.

**Comment by INBOXWISE** [comment]
Thanks for citing the relevant section from RFC 6376. I wasn't aware of that.

I made the request based on how I saw DKIM-Signature in emails sent by open source and commercial MTAs. I'm not sure if the larger signature header would be a problem but I can tell, it's uncommon to include headers that do not present in emails.

I would prefer to have a way to tell KumoMTA that you can sign the specific headers if-present. In my test email, I saw 29 headers included in h= though only 5 needed to be present.

**Comment by MHillyer** [comment]
Syed did you include a header list in your DKIM signing config? The signer should only sign for headers you specify if you did specify a header list.

Sent from a mobile device.
________________________________

**Comment by INBOXWISE** [comment]
Yes, the 29 headers were configured in DKIM signing config and that's why they were added to h=. I basically have to know in advance what headers will present in email and then specify the required headers only in config.

**Comment by MHillyer** [comment]
That is only the case if you do not​ want to assert the absence of those headers when they are not present. Otherwise you can configure h= to the list of all possible headers you want to assert on, knowing that they all get signed for, either their presence or absence. There's not many headers where signing the absence of the header will break something further down the chain, otherwise the header should not be in the list anyway.
________________________________
