### ISSUE TITLE
TSA: Add ability to suspend a queue rather than an egress source.

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#113]
When sending, a user may encounter a remote response that is related more to a given tenant than to the overall IP. If a TSA rule suspends on IP, and that IP is a shared IP, more tenants are affected than is desired.

Given a response pattern, TSA should allow for saying that the queue should be suspended, rather than the egress source. This means that rather than shutting down the IP temporarily, we instead shut down the mail within the IP that the remote MBP has an issue with.

This rule should allow for selective granularity so that the extent of the queue suspension can be managed. If the response the user is writing a rule for is about the content of the message itself, the rule can fire on the tenant-campaign level. If it seems to be about the sending domain, the rule can fire on the tenant level.

This could be two rules: SuspendTenant and SuspendCampaign, if SuspendCampaign is selected and there is no campaign identified a predictable fallback should be performed and documented. I'd suggest it escalates to a SuspendTenant since the goal is to stop the undesirable mail from flowing.

**Comment by wez** [comment]
To support this is actually a bit difficult.  TSA is scoped to egress paths and we have a fairly simple and well-defined config resolution for egress paths, coupled with a slightly obnoxious hack to allow suspension metadata to be bundled along with TSA config overrides.

Since this issue is expanding the scope to scheduled queues there needs to be additional infrastructure added.
The right way to go about this is:

1. Don't treat this as an expansion of the scope of the config, but instead, fixing up the TSA suspension infrastructure, which requires adding a periodic suspension state checker on each MTA node to hit a new and different TSA endpoint that will retrieve suspension data.  It will then translate and apply suspensions to the local set.  This would allow removal of the aforementioned hack, and can then be extended to suspensions scoped to scheduled queues

2. Separately, in the future, we *could* consider allowing TSA rules to alter scheduled queue parameters but I think this is a **bad** idea and will resist it unless a really super compelling argument emerges for it:
   * Scheduled queue parameters are primarily local policy that affect local system tuning and load management for messages that are unlikely to be delivered.
   * egress_pool: the future plan is to make this option have fallbacks that will automatically kick in based on suspensions, so I'm excluding it from the following discussion
   * The retry interval should primarily be set based on the nature of the message. eg: password resets should probably have short intervals and short max age. Other less timely mail can be closer to the defaults. Remote policy should have no impact on the fundamental nature of the mail.
   * The retry interval is perhaps the thing that most people will be tempted to vary, but in the context of TSA, it won't have the effect they think it will:
      * TSA overrides lag behind the triggering event by a short time, and for the scheduled queue, changing the retry parameters will only impact messages that are *received* or *requeued* **after** that point.
      * It won't change the behavior of existing scheduled messages; making it retroactively apply is a non-trivial and very expensive operation that will tank performance because it will require examining every message in the associated scheduled queue and the queue data structure does not support that kind of random access operation. Triggering that with any kind of queue build up will really really harm performance of the system overall.  Not only that, but in the context of how TSA works (loading overrides periodically) there is no defining event from which to trigger this kind of queue sweeping operation so that we only do it once when the config is changed.
      * For messages that have already made several delivery attempts, the chances are small that the mail will ever be delivered anyway so making the retry interval smaller is unlikely to improve the outcome, and making it longer less so.
   * Suspension is the most logical and likely to be effective action that could be taken in the context of the scheduled queue, and we would be able to do that without having scheduled queue parameter overrides.
