### ISSUE TITLE
Clustered Traffic Shaping

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#41]

**Comment by wez** [comment]
The piece we don't currently have is Redis-enabled connection limits.
Part of this work is to do something similar to https://docs.kumomta.com/reference/kumo/configure_redis_throttles/ but for limits.

**Comment by wez** [comment]
Looking at this some more, to make connection limits distributed, what we really need here are distributed semaphores.
Some homework on those reveals a couple of techniques:

* Using `BLPOP` (blocking) or `LPOP` (immediate non-blocking check) to acquire an available slot. https://davidverhasselt.com/a-distributed-mutex-and-semaphore-using-redis/ and their ruby implementation in https://github.com/dv/redis-semaphore This has an open issue about the semaphores getting broken over time; could be misuse of the auto-expiration feature, or a side effect of non-persistent keys being evicted under memory pressure
* https://github.com/swarthy/redis-semaphore#semaphore and https://github.com/swarthy/redis-semaphore#redlocksemaphore. The latter uses the [Redlock algorithm](https://redis.io/docs/manual/patterns/distributed-locks/) which has better guarantees/properties when redis clusters are used
* [This java implementation](https://github.com/redisson/redisson/blob/e9505f7973e25604f69ffb92d4b73db1bf705c79/redisson/src/main/java/org/redisson/RedissonSemaphore.java#L46) which I'm hoping not to have to try to read in too much detail

My quick take: the `BLPOP` approach is the simplest approach and may be the easiest to implement quickly to get things off the ground, but we'll probably want the redlock-based semaphore in the end.

In terms of work that needs to be done here, there are a couple of passes:

* Convert existing limit code to be patterned after a semaphore acquisition/release rather than the current simple counter operations
* Establish a redis semaphore client, perhaps in our throttle crate, perhaps in its own crate. Definitely want some integration tests that spin up redis for this.
* Adjust `configure_redis_throttles` to switch out the limit implementation as mentioned above
