### ISSUE TITLE
Need a better queue purge process

### ISSUE THREAD

**Issue by tommairs** [KumoCorp/kumomta#75]
### What Operating System are you seeing this problem on?

CBL-Mariner/Linux

### What Hardware is this system running?

Azure Standard VM

### KumoMTA version

kumod 2023.07.22-d4ae999a

### Did you try the latest release to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version that I tried

### Describe the bug

In testing, I managed to generate a decent-sized deferred spool of 1.3Gb That is not huge so I expected the admin-bounce API to clear those out quickly, but the config seems to be mangled in a way that is not allowing delivery of the bounces either, so that is just causing the deferred queue to grow and consume resources.  It has effectively locked the server and running with debug reporting I see it constantly posting an overuse of RAM.

```
2023-03-25T20:06:17.338989Z DEBUG memory-monitor kumod::memory: memory usage 30.72 GB, limit 23.45 GB
2023-03-25T20:07:01.745518Z DEBUG memory-monitor kumod::memory: memory usage 30.72 GB, limit 23.45 GB
2023-03-25T20:07:32.051476Z DEBUG memory-monitor kumod::memory: memory usage 30.76 GB, limit 23.45 GB
```

Having a method to arbitrarily kill a queue would be helpful.

### Configuration

Not a configuration issue

**Comment by wez** [comment]
I'd like to understand the failure mode here better.

Right now the response to this is to use the bounce API (eg: via `kcli bounce`).
That can't catch in-flight messages (we have to wait for their attempts to timeout before they'll get swept up in the bounce), but both the ready and scheduled queues that match should get removed.

Note that kumomta doesn't generate bounce email, so that cannot be part of the issue that you observed.

However, if you have misconfigured webhooks then you can create a cycle where you log-that-you-logged-that-you-logged-that-you-logged.

There's no command that will help you fix that; the way out is to stop the service and remove the cycle from the configuration, then start it back up again and use `kcli bounce` on the appropriate queues.

**Comment by tommairs** [comment]
This problem was really spawned by a misconfigured webhook (my own fault) that we have since resolved.  The one thing that remains from the original request is the ability to not log the bounces from the bounce command.  For instance, if I accidentally assign a group of messages to the wrong egress source and just want to clear them out and start over, I don't want a billion irrelevant bounce messages clogging up my logs.  something like a --do_no_log option would be handy.
