### ISSUE TITLE
DANE Support

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#8]
DANE for SMTP: https://datatracker.ietf.org/doc/html/rfc7672
DANE in General: https://datatracker.ietf.org/doc/html/rfc6698

TLSA resolution psuedocode: https://datatracker.ietf.org/doc/html/rfc6698#appendix-B.2

Implementing this requires solid DNSSEC support, and I'm not sure whether it currently exists.
Relevant issues in the upstream resolver library:

* https://github.com/bluejekyll/trust-dns/issues/1443
* https://github.com/bluejekyll/trust-dns/issues/1708

In addition, rustls doesn't have first-class support for DANE in general:

* https://github.com/rustls/rustls/issues/816

and it isn't clear how/if we can adapt the data and feed it into it verifier implementation

**Comment by wez** [comment]
I believe that the current status of the dns resolver is that in order to get DNSSEC validation we:

* Need to enable a crate level feature to compile in support for it
* We need to enable validation in the resolver configuration via https://docs.kumomta.com/reference/kumo.dns/configure_resolver/
* The consequence then is that all domains that are not signed (which is the vast majority) will effectively fail to resolve

That's an obviously untenable situation for us.

An alternative might be to explicitly configure a separate DNSSEC-only resolver instance and use that for DANE. If we can do that without exposing the bifurcation to the user that might work.

**Comment by wez** [comment]
The status of my current analysis is:

* Without a high-fidelity DNSSEC enabled resolver, it is pointless to try to implement DANE; it provides no advantage over our existing `OpportunisticInsecure` TLS mode of operation, and in fact it could be harmful to attempt to use DANE information without correctly validating it.  We cannot try to fill in the gaps by eg: making two queries with verification enabled and disabled, because there isn't enough information present in the responses to determine whether a domain is unsigned or failed to verify.
* Assuming that we're able to extend trust-dns-resolver or source an alternative resolver, the next hurdle is correctly verifying the certificates presented during the TLS handshake.  We need to propagate the set of TLSA records through to the connector and feed it into the certificate verifier, which requires the ability to parse and match.

The best way forward for us and the ecosystem is for trust-dns-resolver and rustls to be extended to support those things.

An alternative way forward is to source an alternative resolver (perhaps by embedding one via FFI) and switching to openssl for the transport security.  It is unclear whether that would be faster to implement, but would have the advantage that the verification logic could then be borrowed from eg: postfix's implementation approach.

**Comment by wez** [comment]
Will try getting this into the rust openssl wrapper and tackling it that way.
Here's my PR for the first part of this:
* https://github.com/sfackler/rust-openssl/pull/2057
